use_frameworks!

platform :ios, '9.0'

target 'BBaseRouter_Example' do
  pod 'BBaseRouter', :path => '../'

  target 'BBaseRouter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
